name: GitHub to Discord Webhook

on:
  push:
    branches:
      - main  # Change this to match your branch

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "🚀 New commit pushed: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"}' \
               "$DISCORD_WEBHOOK"
